import 'package:flutter/material.dart';

const Color background = Color(0xFF131F34);
const Color whitecolor = Colors.white;
const Color greencolor = Color(0xFF77C64A);
const Color bordercolor = Color(0xFF394A69);
const Color hintcolor = Color(0xFF919AA1);
const Color bordererror = Colors.red;
const Color dropdownhint = Color(0xFF6F7888);
const Color blackcolor = Colors.black;
const Color dropdownborder = Color(0xFFE0E0E0);
const Color uploadphoto = Color(0xffF4F7FC);
const Color taptoupload = Color(0xFF707C91);
const Color orangecolor = Color(0xFFE44122);
const Color lightorange = Color(0xFFFEF3F1);
const Color orangeBorder = Color(0xFFFFEBE7);
const Color dividercolor = Color(0xFFE6E6E6);
const Color trackcolor = Color(0xFFDFE0E1);
const Color datecolor = Color(0xFF6C7381);
const Color onthewaycolor = Color(0xFFE8F4E2);
const Color addresstitlecolor = Color(0xFF171210);
const Color ordertitle = Color(0xFF1F1C1C);
const Color yellow = Color(0xFFFEDB41);
const Color lightorange2 = Color(0xFFFC0D1E);
const Color lightPink = Color(0xFFFCEBE8);
